### PR TITLE
Feat/ticket link

### PR DESCRIPTION
**Pull request by ro-ka**
Would be cool, to use an SVG, but I don't have a working editor. This solution has two "problems": No transition working and it looks a bit weird when rotating (wanted a `-3deg` rotation). At least in Firefox, didn't test more.

Small screen:
screen shot 2014-12-07 at 14 10 01

Bigger screen:
screen shot 2014-12-07 at 14 10 08

### CODE REVIEW

**Comment by ro-ka** [comment]
Finally, an update! What about this?

ticket-link

**Comment by robertkowalski** [comment]
looks nice. btw should it be a target blank? i am not sure about our
current way (no target blank) as when i visit a conference site, i often
first check the price but then want to read more about the conference

**Comment by ro-ka** [comment]
Can add a target _blank!

**Comment by ro-ka** [comment]
It already has a target blank, btw!

**Comment by robertkowalski** [comment]
awesome!

**Pull request merged**
